my.service:
  enabled: false
  remote-address: 192.168.50.216
  security:
    username: freelife
    password: 1234
    roles:
    - USER
    - MANAGER
  attrs:
    hasWriteAuthority: false
    hasReadAuthority: true
    hasDeleteAuthority: false